name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        if: ${{ github.event_name != 'pull_request' }}
        uses: snyk/actions/node@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --severity-threshold=high

      - name: Run OSSAR scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/ossar-action@v1

      - name: Run CodeQL Analysis
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/analyze@v2
